# Site settings
title: 'St. Paul&#39;s' # Your Title
tagline: 'Malone, Wisconsin' # A brief tagline for your site
sidebar_image: /images/cover.jpg
categories: [page, post, other]
site-categories: page
include: ["_pages"]
permalink: /:title/

# Build settings
markdown: redcarpet
highlighter: pygments
baseurl: /strange_case # the subpath of your site, e.g. /blog/
